### Leer todas las marcas
GET {{hostname}}/brands

### Crear una marca
POST {{hostname}}/brands
Content-Type: application/json

{
  "name": "Coca Cola"
}

### Editar una marca
PUT {{hostname}}/brands

### Eliminar una marca
DELETE {{hostname}}/brands
