### Leer todas las marcas
GET {{hostname}}/brands

### Leer una sola marca
GET {{hostname}}/brands/1

### Crear una marca
POST {{hostname}}/brands
Content-Type: application/json

{
  "name": "Molinos Río de la Plata"
}

### Editar una marca
PUT {{hostname}}/brands

### Eliminar una marca
DELETE {{hostname}}/brands
