### Leer todas las categorías
GET {{hostname}}/categories

### Leer una categoría
GET {{hostname}}/categories/2

### Crear una categoría
POST {{hostname}}/categories
Content-Type: application/json

{
  "name": "Almacén"
}

### Editar una categoría
PUT {{hostname}}/categories

### Borrar una categoría
DELETE {{hostname}}/categories
