### Leer todas las categorías
GET {{hostname}}/categories

### Crear una categoría
POST {{hostname}}/categories
Content-Type: application/json

{
  "name": "Gaseosas"
}

### Editar una categoría
PUT {{hostname}}/categories

### Borrar una categoría
DELETE {{hostname}}/categories
