#### Obtener todos los productos
GET {{hostname}}/products

#### Filtrar paginando
GET {{hostname}}/products?limit=3&offset=1

#### Filtrar por precio
GET {{hostname}}/products?minPrice=400&maxPrice=600

#### Obtener producto por su ID
GET {{hostname}}/products/8

### Crear un producto
POST {{hostname}}/products
Content-Type: application/json
//Authorization: {{token}}

{
  "name": "Leche entera",
  "description": "Leche entera, 1 lt.",
  "price": 290,
  "stock":701,
  "expires": "2023-05-05",
  "batch": "AB0063",
  "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTldY2GzUZcUtlzu-49eHVjfM4NyfZJWgabAw&usqp=CAU",
  "brandId": 4,
  "categoriesId":[3,4]
}

### Modificar producto
PUT {{hostname}}/products/8
Content-Type: application/json

{
   "categoriesId":[4]
}

### Agrega una categoría relacionada a un producto
PUT  {{hostname}}/products/8/category/4
Content-Type: application/json

### Borra una categoría relacionada a un producto
DELETE {{hostname}}/products/8/category/4
Content-Type: application/json

### Borrar producto
DELETE {{hostname}}/products/3


