### Obtener todos los usuarios
GET {{hostname}}/users

### Traer un solo usuario
GET {{hostname}}/users/emily@mail.com


### Nuevo usuario
POST {{hostname}}/users
Content-Type: application/json

{
  "name":"Emily",
  "lastname":"Rvgn",
  "email":"emily@mail.com",
  "password": "123456",
  "phone": "0303456",
  "role":"admin"
}

### Modificar usuario
PUT {{hostname}}/users/pansa@mail.com
Content-Type: application/json

{
	"role":"admin"
}

### Borrar usuario
DELETE {{hostname}}/users/63d94a947476cb97670c9848


